Repository jfrog/terraform-provider-artifactory, pull requests merged in 2021-03, with the labels that each got.

#36 Add xray policy and watch resources
  .env
  README.md
  docker-compose.yaml
  go.mod
  go.sum
  pkg/artifactory/provider.go
  pkg/artifactory/resource_artifactory_user.go
  pkg/artifactory/resource_xray_policy.go
  pkg/artifactory/resource_xray_policy_test.go
  pkg/artifactory/resource_xray_watch.go
  pkg/artifactory/resource_xray_watch_test.go
  sample.tf
Labels: enhancement

#47 Fix crash bug. Tests need an overhaul
  pkg/artifactory/provider.go
  pkg/artifactory/resource_artifactory_user.go
Labels: bug

#49 PTRENG-1790 - Hopefully the next poor soul will be better off than me
  Dockerfile
  README.md
Labels: documentation

#51 Add xray docs for policy and watch resources
  docs/resources/artifactory_xray_policy.md
  docs/resources/artifactory_xray_watch.md
Labels: documentation
