Repository jfrog/terraform-provider-artifactory, pull requests merged in 2021-11, with the labels that each got.

#200 GH-196 group bug
  pkg/artifactory/resource_artifactory_group.go
  sample.tf
Labels: bug, rt

#206 GH-20 password replication issue
  pkg/artifactory/resource_artifactory_remote_repository.go
  pkg/artifactory/resource_artifactory_replication_config.go
  pkg/artifactory/resource_artifactory_replication_config_test.go
  pkg/artifactory/resource_artifactory_single_replication_config.go
  pkg/artifactory/resource_artifactory_single_replication_config_test.go
Labels: bug

#202 GH-23 npm local support
  docs/resources/artifactory_local_bower_repository.md
  docs/resources/artifactory_local_chef_repository.md
  docs/resources/artifactory_local_cocoapods_repository.md
  docs/resources/artifactory_local_composer_repository.md
  docs/resources/artifactory_local_conan_repository.md
  docs/resources/artifactory_local_cran_repository.md
  docs/resources/artifactory_local_gems_repository.md
  docs/resources/artifactory_local_generic_repository.md
  docs/resources/artifactory_local_gitlfs_repository.md
  docs/resources/artifactory_local_go_repository.md
  docs/resources/artifactory_local_helm_repository.md
  docs/resources/artifactory_local_ivy_repository.md
  docs/resources/artifactory_local_npm_repository.md
  docs/resources/artifactory_local_opkg_repository.md
  docs/resources/artifactory_local_puppet_repository.md
  docs/resources/artifactory_local_pypi_repository.md
  docs/resources/artifactory_local_sbt_repository.md
  docs/resources/artifactory_local_vagrant_repository.md
  pkg/artifactory/provider.go
  pkg/artifactory/repositories.go
  pkg/artifactory/resource_artifactory_local_generic_repository.go
  pkg/artifactory/resource_artifactory_local_repository_test.go
  sample.tf
Labels: enhancement, rt

#209 Simplifications
  pkg/artifactory/repositories.go
  pkg/artifactory/resource_artifactory_general_security.go
  pkg/artifactory/resource_artifactory_keypair.go
  pkg/artifactory/resource_artifactory_local_alpine_repository.go
  pkg/artifactory/resource_artifactory_local_debian_repository.go
  pkg/artifactory/resource_artifactory_local_docker_repository.go
  pkg/artifactory/resource_artifactory_local_java_repository.go
  pkg/artifactory/resource_artifactory_local_nuget_repository.go
  pkg/artifactory/resource_artifactory_local_repository.go
  pkg/artifactory/resource_artifactory_local_repository_test.go
  pkg/artifactory/resource_artifactory_local_rpm_repository.go
  pkg/artifactory/resource_artifactory_permission_target.go
  pkg/artifactory/resource_artifactory_remote_cargo_repository.go
  pkg/artifactory/resource_artifactory_remote_docker_repository.go
  pkg/artifactory/resource_artifactory_remote_helm_repository.go
  pkg/artifactory/resource_artifactory_remote_repository.go
  pkg/artifactory/resource_artifactory_virtual_go_repository.go
  pkg/artifactory/resource_artifactory_virtual_maven_repository.go
  pkg/artifactory/resource_artifactory_virtual_repository.go
  pkg/artifactory/util.go
Labels: enhancement

#210 PTRENG-3249, RT provider, fix keypair tests failure. Removed username…
  docs/resources/artifactory_keypair.md
  docs/resources/artifactory_local_alpine_repository.md
  docs/resources/artifactory_local_debian_repository.md
  pkg/artifactory/provider.go
  pkg/artifactory/resource_artifactory_keypair.go
  pkg/artifactory/resource_artifactory_keypair_test.go
  pkg/artifactory/resource_artifactory_local_repository_test.go
  sample.tf
  scripts/run-artifactory.sh
Labels: rt
