Repository jfrog/terraform-provider-artifactory, pull requests merged in 2023-10, with the labels that each got.

#816 fix store_artifacts_locally docs to reflect reality
  docs/resources/remote.md
Labels: documentation, no changelog

#817 Migrate artifactory distribution public key to framework
  CHANGELOG.md
  pkg/artifactory/provider/framework.go
  pkg/artifactory/provider/resources.go
  pkg/artifactory/resource/configuration/resource_artifactory_backup.go
  pkg/artifactory/resource/security/resource_artifactory_certificate.go
  pkg/artifactory/resource/security/resource_artifactory_certificate_test.go
  pkg/artifactory/resource/security/resource_artifactory_distribution_public_key.go
  pkg/artifactory/resource/security/resource_artifactory_distribution_public_key_test.go
Labels: enhancement

#820 Remove default value for `artifactory_scoped_token.expires_in`
  CHANGELOG.md
  docs/resources/scoped_token.md
  pkg/artifactory/resource/security/resource_artifactory_scoped_token.go
  pkg/artifactory/resource/security/resource_artifactory_scoped_token_test.go
Labels: bug

#819 Add resource for mail server
  CHANGELOG.md
  docs/resources/mail_server.md
  examples/resources/artifactory_mail_server/import.sh
  examples/resources/artifactory_mail_server/resource.tf
  go.mod
  go.sum
  pkg/artifactory/provider/framework.go
  pkg/artifactory/provider/provider.go
  pkg/artifactory/provider/sdkv2.go
  pkg/artifactory/resource/configuration/resource_artifactory_backup.go
  pkg/artifactory/resource/configuration/resource_artifactory_backup_test.go
  pkg/artifactory/resource/configuration/resource_artifactory_mail_server.go
  pkg/artifactory/resource/configuration/resource_artifactory_mail_server_test.go
  pkg/artifactory/resource/security/resource_artifactory_distribution_public_key_test.go
  pkg/artifactory/resource/security/resource_artifactory_permission_target_test.go
  pkg/artifactory/resource/security/resource_artifactory_scoped_token_test.go
  pkg/artifactory/resource/user/resource_artifactory_anonymous_user_test.go
  pkg/artifactory/resource/user/resource_artifactory_managed_user_test.go
  pkg/artifactory/resource/user/resource_artifactory_user_test.go
  templates/resources/mail_server.md.tmpl
Labels: enhancement

#826 Migrate artifactory_certificate resource to terraform-plugin-framework
  CHANGELOG.md
  docs/resources/certificate.md
  pkg/artifactory/provider/framework.go
  pkg/artifactory/provider/resources.go
  pkg/artifactory/resource/security/resource_artifactory_certificate.go
  pkg/artifactory/resource/security/resource_artifactory_certificate_test.go
Labels: enhancement

#829 Migrate artifactory_keypair resource to terraform-plugin-framework
  CHANGELOG.md
  docs/resources/keypair.md
  pkg/artifactory/datasource/repository/federated/datasource_artifactory_federated_repository_test.go
  pkg/artifactory/datasource/repository/local/datasource_artifactory_local_repository_test.go
  pkg/artifactory/datasource/repository/virtual/datasource_artifactory_virtual_repository_test.go
  pkg/artifactory/provider/framework.go
  pkg/artifactory/provider/resources.go
  pkg/artifactory/resource/repository/federated/resource_artifactory_federated_repository_test.go
  pkg/artifactory/resource/repository/local/resource_artifactory_local_repository_test.go
  pkg/artifactory/resource/repository/virtual/resource_artifactory_virtual_repository_test.go
  pkg/artifactory/resource/security/resource_artifactory_certificate.go
  pkg/artifactory/resource/security/resource_artifactory_distribution_public_key.go
  pkg/artifactory/resource/security/resource_artifactory_keypair.go
  pkg/artifactory/resource/security/resource_artifactory_keypair_test.go
  pkg/artifactory/resource/security/security.go
Labels: enhancement

#830 Remove length validation for optional attribute
  CHANGELOG.md
  pkg/artifactory/resource/configuration/resource_artifactory_mail_server.go
Labels: enhancement

#832 Prioritize access token over api key
  CHANGELOG.md
  docs/index.md
  pkg/artifactory/provider/framework.go
  pkg/artifactory/provider/sdkv2.go
Labels: enhancement

#834 Make provider attributes match between SDKv2 and framework providers
  CHANGELOG.md
  pkg/artifactory/provider/framework.go
  pkg/artifactory/provider/sdkv2.go
  sample.tf
Labels: bug
