Repository jfrog/terraform-provider-artifactory, pull requests merged in 2023-12, with the labels that each got.

#851 Fix global environment
  CHANGELOG.md
  pkg/artifactory/resource/security/resource_artifactory_access_token_test.go
  pkg/artifactory/resource/security/resource_artifactory_global_environment.go
Labels: bug

#850 Fix empty error when updating user
  .github/workflows/release.yml
  CHANGELOG.md
  go.mod
  go.sum
  pkg/artifactory/resource/configuration/resource_artifactory_ldap_group_setting_v2.go
  pkg/artifactory/resource/configuration/resource_artifactory_ldap_setting_v2.go
  pkg/artifactory/resource/security/resource_artifactory_certificate.go
  pkg/artifactory/resource/security/resource_artifactory_distribution_public_key.go
  pkg/artifactory/resource/security/resource_artifactory_global_environment.go
  pkg/artifactory/resource/security/resource_artifactory_group.go
  pkg/artifactory/resource/security/resource_artifactory_keypair.go
  pkg/artifactory/resource/security/resource_artifactory_scoped_token.go
  pkg/artifactory/resource/user/resource_artifactory_anonymous_user.go
  pkg/artifactory/resource/user/user.go
  pkg/artifactory/resource/user/user_fw.go
Labels: bug, dependencies

#855 Add file listing data source
  CHANGELOG.md
  docs/data-sources/file_list.md
  examples/data-sources/artifactory_file_list/data-source.tf
  examples/data-sources/repositories/data-source.tf
  pkg/artifactory/datasource/artifact/datasource_artifactory_file.go
  pkg/artifactory/datasource/artifact/datasource_artifactory_file_list.go
  pkg/artifactory/datasource/artifact/datasource_artifactory_file_list_test.go
  pkg/artifactory/datasource/artifact/datasource_artifactory_file_test.go
  pkg/artifactory/datasource/artifact/datasource_artifactory_fileinfo.go
  pkg/artifactory/provider/datasources.go
  pkg/artifactory/provider/framework.go
Labels: enhancement

#854 docs: the indentation of scoped_token.md to a natural form
  docs/resources/scoped_token.md
Labels: documentation

#859 Downgrade Resty to avoid CVE
  CHANGELOG.md
  go.mod
  go.sum
  pkg/acctest/test.go
Labels: dependencies
