Repository jfrog/terraform-provider-artifactory, pull requests merged in 2024-08, with the labels that each got.

#1043 Add 'max_unique_snapshots' attribute to Java package types for remote repos
  CHANGELOG.md
  docs/resources/remote_gradle_repository.md
  docs/resources/remote_ivy_repository.md
  docs/resources/remote_maven_repository.md
  docs/resources/remote_sbt_repository.md
  pkg/artifactory/resource/repository/remote/remote.go
  pkg/artifactory/resource/repository/remote/resource_artifactory_remote_repository_test.go
Labels: enhancement

#1046 Add resource for repository properties
  .github/workflows/acceptance-tests.yml
  CHANGELOG.md
  docs/resources/artifact.md
  docs/resources/item_properties.md
  examples/resources/artifactory_item_properties/import.sh
  examples/resources/artifactory_item_properties/resource.tf
  pkg/artifactory/provider/framework.go
  pkg/artifactory/resource/artifact/resource_artifactory_artifact.go
  pkg/artifactory/resource/artifact/resource_artifactory_artifact_test.go
  pkg/artifactory/resource/artifact/resource_artifactory_item_properties.go
  pkg/artifactory/resource/artifact/resource_artifactory_item_properties_test.go
Labels: enhancement

#1050 Fix incorrect query param string for deleting item properties
  CHANGELOG.md
  pkg/artifactory/resource/artifact/resource_artifactory_item_properties.go
Labels: bug

#1051 Fix virtual go repo external_dependencies_patterns still force replacement on update
  CHANGELOG.md
  pkg/artifactory/resource/repository/virtual/resource_artifactory_virtual_go_repository.go
  pkg/artifactory/resource/repository/virtual/resource_artifactory_virtual_repository_test.go
  scripts/run-artifactory-container.sh
Labels: bug

#1052 Deprecate 'artifactory_saml_settings' resource
  CHANGELOG.md
  docs/resources/permission_target.md
  docs/resources/release_bundle_custom_webhook.md
  docs/resources/release_bundle_v2.md
  docs/resources/release_bundle_v2_promotion.md
  docs/resources/release_bundle_webhook.md
  docs/resources/saml_settings.md
  pkg/artifactory/resource/configuration/resource_artifactory_saml_settings.go
Labels: enhancement

#1056 Add `artifactory_package_cleanup_policy` resource
  .github/workflows/acceptance-tests.yml
  .github/workflows/release.yml
  CHANGELOG.md
  docs/index.md
  docs/resources/package_cleanup_policy.md
  examples/resources/artifactory_package_cleanup_policy/import.sh
  examples/resources/artifactory_package_cleanup_policy/resource.tf
  pkg/artifactory/datasource/artifact/datasource_artifactory_file_list.go
  pkg/artifactory/provider/framework.go
  pkg/artifactory/resource/artifact/resource_artifactory_artifact.go
  pkg/artifactory/resource/configuration/resource_artifactory_general_security.go
  pkg/artifactory/resource/configuration/resource_artifactory_package_cleanup_policy.go
  pkg/artifactory/resource/configuration/resource_artifactory_package_cleanup_policy_test.go
  pkg/artifactory/resource/configuration/resource_artifactory_property_set.go
  pkg/artifactory/resource/configuration/resource_artifactory_repository_layout.go
  pkg/artifactory/resource/security/resource_artifactory_password_expiration_policy.go
  pkg/artifactory/resource/security/resource_artifactory_user_lock_policy.go
  scripts/run-artifactory-container.sh
  scripts/run-artifactory.sh
  scripts/system.yaml
  scripts/wait-for-rt.sh
Labels: enhancement

#1058 Fix: remove unwanted line that was part of old config option metadata…
  docs/resources/remote_maven_repository.md
Labels: no changelog

#1059 Migrate `artifactory_local_repository_single_replication' to plugin framework
  CHANGELOG.md
  docs/resources/local_repository_single_replication.md
  pkg/artifactory/provider/framework.go
  pkg/artifactory/provider/resources.go
  pkg/artifactory/resource/replication/replication.go
  pkg/artifactory/resource/replication/resource_artifactory_local_repository_multi_replication.go
  pkg/artifactory/resource/replication/resource_artifactory_local_repository_single_replication.go
  pkg/artifactory/resource/replication/resource_artifactory_local_repository_single_replication_test.go
  pkg/artifactory/resource/replication/resource_artifactory_remote_repository_replication.go
Labels: enhancement
