Repository jfrog/terraform-provider-artifactory, pull requests merged in 2024-01, with the labels that each got.

#861 Remove duplicate attribute
  docs/resources/local_repository_single_replication.md
Labels: documentation, no changelog

#863 Add opentofu to pipeline matrix steps
  .jfrog-pipelines/TFproviderTest.yml
Labels: no changelog, opentofu

#868 Improve doc for artifactory file resource
  CHANGELOG.md
  README.md
  docs/data-sources/file.md
  docs/index.md
  pkg/artifactory/datasource/artifact/datasource_artifactory_file.go
  sample.tf
  scripts/run-artifactory.sh
Labels: documentation

#869 Add project_id attribute to remote docker repo resource
  CHANGELOG.md
  docs/resources/remote_docker_repository.md
  go.mod
  go.sum
  pkg/artifactory/resource/repository/remote/resource_artifactory_remote_docker_repository.go
  pkg/artifactory/resource/repository/remote/resource_artifactory_remote_repository_test.go
Labels: enhancement

#871 Migrate 'artifactory_proxy' resource to plugin-framework
  CHANGELOG.md
  pkg/artifactory/provider/framework.go
  pkg/artifactory/provider/resources.go
  pkg/artifactory/resource/configuration/resource_artifactory_proxy.go
  pkg/artifactory/resource/configuration/resource_artifactory_proxy_test.go
  pkg/artifactory/resource/repository/remote/resource_artifactory_remote_repository_test.go
Labels: enhancement

#875 Add 'x' and 's' to artifactory_scoped_token "scopes" attribute validation
  CHANGELOG.md
  docs/resources/scoped_token.md
  pkg/artifactory/resource/security/resource_artifactory_scoped_token.go
  pkg/artifactory/resource/security/resource_artifactory_scoped_token_test.go
Labels: bug

#876 Fix LDAP attribute validations when values are from variable
  CHANGELOG.md
  pkg/artifactory/resource/configuration/resource_artifactory_ldap_group_setting_v2.go
  pkg/artifactory/resource/configuration/resource_artifactory_ldap_group_setting_v2_test.go
  pkg/artifactory/resource/configuration/resource_artifactory_ldap_setting_v2.go
  pkg/artifactory/resource/configuration/resource_artifactory_ldap_setting_v2_test.go
Labels: bug

#877 Replace "<" and ">" in `scopes` attribute descriptions in `artifactory_scoped_token` resource
  docs/resources/scoped_token.md
  pkg/artifactory/resource/security/resource_artifactory_scoped_token.go
Labels: documentation, no changelog
