Repository jfrog/terraform-provider-artifactory, pull requests merged in 2024-11, with the labels that each got.

#1113 Fix unknown value error for 'check_binary_existence_in_filestore'
  CHANGELOG.md
  pkg/artifactory/resource/replication/replication_test.go
  pkg/artifactory/resource/replication/resource_artifactory_local_repository_single_replication.go
  pkg/artifactory/resource/replication/resource_artifactory_local_repository_single_replication_test.go
Labels: bug

#1114 Update version to 12.3.3
  README.md
  docs/index.md
  sample.tf
Labels: documentation

#1123 Check for attribute value being null or unknown before using it for validation
  CHANGELOG.md
  pkg/artifactory/resource/configuration/resource_artifactory_ldap_group_setting_v2.go
  pkg/artifactory/resource/configuration/resource_artifactory_repository_layout.go
  pkg/artifactory/resource/lifecycle/resource_artifactory_release_bundle_v2.go
  pkg/artifactory/resource/security/resource_artifactory_vault_configuration.go
  pkg/artifactory/resource/user/user.go
  pkg/artifactory/resource/webhook/resource_artifactory_custom_webhook_build.go
  pkg/artifactory/resource/webhook/resource_artifactory_custom_webhook_release_bundle.go
  pkg/artifactory/resource/webhook/resource_artifactory_custom_webhook_release_bundle_v2.go
  pkg/artifactory/resource/webhook/resource_artifactory_custom_webhook_release_bundle_v2_promotion.go
  pkg/artifactory/resource/webhook/resource_artifactory_custom_webhook_repo.go
  pkg/artifactory/resource/webhook/resource_artifactory_webhook_build.go
  pkg/artifactory/resource/webhook/resource_artifactory_webhook_release_bundle.go
  pkg/artifactory/resource/webhook/resource_artifactory_webhook_release_bundle_v2.go
  pkg/artifactory/resource/webhook/resource_artifactory_webhook_release_bundle_v2_promotion.go
  pkg/artifactory/resource/webhook/resource_artifactory_webhook_repo.go
Labels: bug

#1126 Relax validations for search_criteria attributes for cleanup policy resource
  CHANGELOG.md
  pkg/artifactory/resource/configuration/resource_artifactory_package_cleanup_policy.go
  pkg/artifactory/resource/configuration/resource_artifactory_package_cleanup_policy_test.go
Labels: bug

#1130 Deprecate group resource
  CHANGELOG.md
  docs/resources/group.md
  pkg/artifactory/resource/security/resource_artifactory_group.go
Labels: enhancement

#1136 Update Resty to 2.16.2
  CHANGELOG.md
  go.mod
  go.sum
Labels: dependencies
