Repository jfrog/terraform-provider-artifactory, pull requests merged in 2024-06, with the labels that each got.

#984 Move 'metadata_retrieval_timeout_secs' to remote.md
  CHANGELOG.md
  docs/resources/remote.md
  docs/resources/remote_maven_repository.md
Labels: documentation

#986 Fix actions validation in scopes attribute
  CHANGELOG.md
  pkg/artifactory/resource/security/resource_artifactory_scoped_token.go
  pkg/artifactory/resource/security/resource_artifactory_scoped_token_test.go
Labels: bug

#993 Fx build webhook validation
  CHANGELOG.md
  pkg/artifactory/resource/webhook/resource_artifactory_webhook_build.go
  pkg/artifactory/resource/webhook/resource_artifactory_webhook_test.go
Labels: bug

#996 Correct data-sources docs use `data`, not `resource`
  docs/data-sources/federated_cargo_repository.md
  docs/data-sources/local_docker_v1_repository.md
  docs/data-sources/local_docker_v2_repository.md
  docs/data-sources/local_helmoci_repository.md
  docs/data-sources/local_maven_repository.md
  docs/data-sources/local_oci_repository.md
  docs/data-sources/local_terraform_module_repository.md
Labels: documentation

#997 Add GitHub workflow for acceptance tests
  .github/workflows/acceptance-tests.yml
  .gitignore
  GNUmakefile
  README.md
  go.mod
Labels: enhancement

#998 Skip tests when running with tofu
  .github/workflows/acceptance-tests.yml
  CHANGELOG.md
  GNUmakefile
  pkg/artifactory/resource/configuration/resource_artifactory_proxy_test.go
  pkg/artifactory/resource/configuration/resource_artifactory_saml_settings_test.go
  pkg/artifactory/resource/repository/remote/resource_artifactory_remote_repository_test.go
  pkg/artifactory/resource/security/resource_artifactory_certificate_test.go
  pkg/artifactory/resource/security/resource_artifactory_distribution_public_key_test.go
  pkg/artifactory/resource/security/resource_artifactory_group_test.go
  pkg/artifactory/resource/security/resource_artifactory_keypair_test.go
  pkg/artifactory/resource/security/resource_artifactory_permission_target_test.go
  pkg/artifactory/resource/security/resource_artifactory_scoped_token_test.go
  pkg/artifactory/resource/user/resource_artifactory_managed_user_test.go
  pkg/artifactory/resource/user/resource_artifactory_user_test.go
  pkg/artifactory/resource/webhook/resource_artifactory_webhook_test.go
Labels: enhancement

#1003 Add allow content browsing to all remote repos
  CHANGELOG.md
  pkg/artifactory/provider/framework.go
  pkg/artifactory/provider/sdkv2.go
  pkg/artifactory/resource/repository/remote/remote.go
  pkg/artifactory/resource/repository/remote/resource_artifactory_remote_repository_test.go
Labels: enhancement

#1005 Remove 'ForceNew' setting from external_dependencies_patterns attribute
  CHANGELOG.md
  pkg/acctest/test.go
  pkg/artifactory/resource/repository/virtual/resource_artifactory_virtual_repository_test.go
  pkg/artifactory/resource/repository/virtual/virtual.go
Labels: bug

#1007 Add '+' character to the allowed list for user `name` attribute
  CHANGELOG.md
  docs/resources/managed_user.md
  docs/resources/unmanaged_user.md
  docs/resources/user.md
  pkg/artifactory/resource/user/user.go
Labels: bug

#1008 Add new resource 'artifactory_vault_configuration'
  .gitignore
  CHANGELOG.md
  docs/resources/vault_configuration.md
  examples/resources/artifactory_vault_configuration/import.sh
  examples/resources/artifactory_vault_configuration/resource.tf
  pkg/acctest/test.go
  pkg/artifactory/datasource/repository/federated/datasource_artifactory_federated_repository_test.go
  pkg/artifactory/datasource/repository/local/datasource_artifactory_local_repository_test.go
  pkg/artifactory/datasource/repository/remote/datasource_artifactory_remote_repository_test.go
  pkg/artifactory/datasource/repository/virtual/datasource_artifactory_virtual_repository_test.go
  pkg/artifactory/provider/framework.go
  pkg/artifactory/provider/sdkv2.go
  pkg/artifactory/resource/configuration/resource_artifactory_backup_test.go
  pkg/artifactory/resource/configuration/resource_artifactory_repository_layout_test.go
  pkg/artifactory/resource/replication/resource_artifactory_pull_replication_test.go
  pkg/artifactory/resource/repository/federated/resource_artifactory_federated_repository_test.go
  pkg/artifactory/resource/repository/local/resource_artifactory_local_repository_test.go
  pkg/artifactory/resource/repository/remote/resource_artifactory_remote_repository_test.go
  pkg/artifactory/resource/repository/repository_test.go
  pkg/artifactory/resource/repository/virtual/resource_artifactory_virtual_repository_test.go
  pkg/artifactory/resource/security/resource_artifactory_scoped_token_test.go
  pkg/artifactory/resource/security/resource_artifactory_vault_configuration.go
  pkg/artifactory/resource/security/resource_artifactory_vault_configuration_test.go
  pkg/artifactory/resource/webhook/resource_artifactory_webhook_test.go
  scripts/access.config.patch.yml
  scripts/run-artifactory-container.sh
  scripts/run-artifactory.sh
  scripts/wait-for-rt.sh
Labels: enhancement
