Repository jfrog/terraform-provider-artifactory, pull requests merged in 2024-09, with the labels that each got.

#1064 Upgrade terraform-plugin-testing package
  CHANGELOG.md
  go.mod
  go.sum
  pkg/artifactory/resource/configuration/resource_artifactory_property_set_test.go
  pkg/artifactory/resource/configuration/resource_artifactory_proxy_test.go
  pkg/artifactory/resource/configuration/resource_artifactory_repository_layout.go
  pkg/artifactory/resource/configuration/resource_artifactory_repository_layout_test.go
  pkg/artifactory/resource/replication/resource_artifactory_local_repository_single_replication_test.go
  pkg/artifactory/resource/repository/remote/remote.go
  pkg/artifactory/resource/repository/remote/resource_artifactory_remote_repository_test.go
  pkg/artifactory/resource/security/resource_artifactory_certificate_test.go
  pkg/artifactory/resource/security/resource_artifactory_distribution_public_key_test.go
  pkg/artifactory/resource/security/resource_artifactory_group_test.go
  pkg/artifactory/resource/security/resource_artifactory_keypair_test.go
  pkg/artifactory/resource/security/resource_artifactory_permission_target_test.go
  pkg/artifactory/resource/security/resource_artifactory_scoped_token_test.go
  pkg/artifactory/resource/user/resource_artifactory_managed_user_test.go
  pkg/artifactory/resource/user/resource_artifactory_unmanaged_user_test.go
  pkg/artifactory/resource/user/resource_artifactory_user_test.go
  pkg/artifactory/resource/user/user.go
Labels: enhancement, no changelog

#1060 Migrate `artifactory_remote_repository_replication` resource to Plugin Framework
  CHANGELOG.md
  README.md
  docs/resources/api_key.md
  docs/resources/pull_replication.md
  docs/resources/push_replication.md
  pkg/artifactory/provider/framework.go
  pkg/artifactory/provider/resources.go
  pkg/artifactory/resource/replication/resource_artifactory_local_repository_single_replication.go
  pkg/artifactory/resource/replication/resource_artifactory_remote_repository_replication.go
  pkg/artifactory/resource/replication/resource_artifactory_remote_repository_replication_test.go
Labels: enhancement

#1061 Migrate `artifactory_local_repository_multi_replication` resource to Plugin Framework
  CHANGELOG.md
  docs/resources/local_repository_multi_replication.md
  pkg/artifactory/provider/framework.go
  pkg/artifactory/provider/resources.go
  pkg/artifactory/resource/replication/replication.go
  pkg/artifactory/resource/replication/resource_artifactory_local_repository_multi_replication.go
  pkg/artifactory/resource/replication/resource_artifactory_local_repository_multi_replication_test.go
  pkg/artifactory/resource/replication/resource_artifactory_local_repository_single_replication.go
  pkg/artifactory/resource/replication/resource_artifactory_local_repository_single_replication_test.go
  pkg/artifactory/resource/replication/resource_artifactory_remote_repository_replication_test.go
Labels: enhancement

#1065 Add 'project_key' attribute to 'artifactory_package_cleanup_policy' resource
  CHANGELOG.md
  docs/resources/package_cleanup_policy.md
  examples/resources/artifactory_package_cleanup_policy/import.sh
  examples/resources/artifactory_package_cleanup_policy/resource.tf
  pkg/artifactory/resource/configuration/resource_artifactory_package_cleanup_policy.go
  pkg/artifactory/resource/configuration/resource_artifactory_package_cleanup_policy_test.go
Labels: enhancement

#1067 Fix: update remote repos document with missing attribute, fix broken …
  docs/resources/package_cleanup_policy.md
  docs/resources/remote.md
Labels: documentation

#1068 Add warning message to artifactory_package_cleanup_policy doc
  CHANGELOG.md
  docs/resources/package_cleanup_policy.md
  pkg/artifactory/resource/configuration/resource_artifactory_package_cleanup_policy.go
  pkg/artifactory/resource/webhook/resource_artifactory_artifact_lifecycle_test.go
  pkg/artifactory/resource/webhook/resource_artifactory_custom_webhook_test.go
  pkg/artifactory/resource/webhook/resource_artifactory_webhook_release_bundle_v2_promotion_test.go
  pkg/artifactory/resource/webhook/resource_artifactory_webhook_test.go
  pkg/artifactory/resource/webhook/resource_artifactory_webhook_user_test.go
  scripts/run-artifactory-container.sh
Labels: documentation

#1071 Upgrade golang for CVE 2024-34156
  .github/workflows/acceptance-tests.yml
  .github/workflows/release.yml
  CHANGELOG.md
  docs/resources/package_cleanup_policy.md
  go.mod
  pkg/artifactory/resource/configuration/resource_artifactory_package_cleanup_policy.go
Labels: documentation, enhancement

#1072 Fix incorrect default value for list_remote_folder_items attribute
  CHANGELOG.md
  pkg/artifactory/resource/replication/resource_artifactory_remote_repository_replication_test.go
  pkg/artifactory/resource/repository/remote/remote.go
  pkg/artifactory/resource/repository/remote/resource_artifactory_remote_repository_test.go
Labels: bug

#1084 Add Cocoapods package type to virtual repo list
  CHANGELOG.md
  docs/resources/virtual_cocoapods_repository.md
  pkg/artifactory/resource/repository/default_repo_layout_map.go
  pkg/artifactory/resource/repository/virtual/virtual.go
Labels: enhancement

#1085 Add 'retrieve_sha256_from_server' attribute to remote generic repo
  CHANGELOG.md
  docs/resources/remote_generic_repository.md
  pkg/artifactory/resource/repository/remote/remote.go
  pkg/artifactory/resource/repository/remote/resource_artifactory_remote_generic_repository.go
  pkg/artifactory/resource/repository/remote/resource_artifactory_remote_repository_test.go
  pkg/artifactory/resource/repository/virtual/resource_artifactory_virtual_repository_test.go
Labels: enhancement
